package de.mineformers.core

import cpw.mods.fml.common.{FMLCommonHandler, LoadController, ModMetadata, DummyModContainer}
import com.google.common.collect.ImmutableList
import com.google.common.eventbus.{Subscribe, EventBus}
import cpw.mods.fml.common.event.FMLPreInitializationEvent
import cpw.mods.fml.common.eventhandler.SubscribeEvent
import de.mineformers.core.event.RenderBlockEvent

class MFCoreContainer extends DummyModContainer(new ModMetadata) {

  val meta = getMetadata
  meta.modId = "mfcore"
  meta.name = "MFCore"
  meta.authorList = ImmutableList.of("PaleoCrafter")
  meta.version = "1.0"
  meta.autogenerated = false

  override def registerBus(bus: EventBus, controller: LoadController): Boolean = {
    bus.register(this)
    true
  }

  @Subscribe
  def preInit(event: FMLPreInitializationEvent): Unit = {
    FMLCommonHandler.instance().bus().register(new Test)
  }

  class Test {
    @SubscribeEvent
    def testEvent(event: RenderBlockEvent.Pre): Unit = {
      System.out.println("Test")
      if (event.renderType == 25) {
        event.renderer.renderStandardBlock(event.block, event.x, event.y, event.z)
        event.setCanceled(true)
      }
    }
  }
}
